---
- name: Download Helm archive
  get_url:
    url: '{{ kubernetes_helm_url }}'
    dest: '/tmp/{{ kubernetes_helm_tgz }}'
    checksum: '{{ kubernetes_helm_checksum }}'
    mode: 0644

- name: Extract helm archive
  unarchive:
    copy: no
    src: '/tmp/{{ kubernetes_helm_tgz }}'
    dest: /tmp
    creates: '/tmp/{{ kubernetes_helm_platform }}'

- name: Copy Helm and Tiller binaries
  copy:
    remote_src: yes
    src: '/tmp/{{ kubernetes_helm_platform }}/{{ item }}'
    dest: '{{ kubernetes_helm_install_dir }}/{{ item }}'
    owner: root
    group: root
    mode: 0755
  loop:
    - helm
    - tiller

- name: Copy RBAC policy for Helm
  template:
    src: templates/helm-rbac-config.yml.j2
    dest: /tmp/helm-rbac-config.yml
    owner: root
    group: root
    mode: 0755

- name: Apply helm RBAC policy
  command: "kubectl apply -f /tmp/helm-rbac-config.yml --namespace kube-system"

- name: Initialize Helm
  command: "helm init --service-account tiller --tiller-namespace kube-system"

- name: Setup Helm for docker user
  command: "helm init --client-only --tiller-namespace kube-system"
  become_user: '{{ docker_user }}'